### ISSUE TITLE
No move operation for span?

### ISSUE THREAD

**Issue by kimtopley** [martinmoene/gsl-lite#10]
There is no move constructor/move assignment for span. Is this intended?

**Comment by martinmoene** [comment]
Thanks for the heads-up. The move-constructor and move-assignment were not missing by intention, it's merely I'm trying to strike *some* balance between pre-C++11 and C++11 and later so that the source remains readable. That said, adding these can hardly be called disturbing ;)

Added to [release 0.1.0.](https://github.com/martinmoene/gsl-lite/releases/tag/v0.1.0).
