### ISSUE TITLE
Use std::span if available

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/gsl-lite#121]
Select std::span or gsl::span

`-Dgsl_CONFIG_SELECT_SPAN=gsl_SPAN_DEFAULT ` / `gsl_SPAN_GSL ` /  `gsl_SPAN_STD`

Plan:
- [ ] Readme
- [ ] gsl-lite.hpp

**Comment by mbeutel** [comment]
I assume the idea is to have `gsl_SPAN_DEFAULT` use `std::span<>` if available, and a dedicated implementation otherwise, right?

Would it also be the default setting? I'd have some concerns about that (which also apply to #120). Consider the following targets in different projects:

- library Foo, targeting C++14, which uses gsl-lite
- executable Bar, targeting C++20, which uses both Foo and gsl-lite

If both projects specify no configuration option for gsl-lite (as they would by default), then this may result in link-time errors (best case) or silent data corruption.

We would get a link-time error if a public header of Foo exposes a function declaration `fooFunc(gsl::byte, gsl::span<int>)` which is called from Bar. When Bar is compiled, gsl-lite aliases the standard types, so the linker generates a reference to `fooFunc(std::byte, std::span<int>)`, but Foo was compiled with C++14 and hence only provides `fooFunc(gsl::actual_byte, gsl::actual_span<int>)` (or whatever the non-aliased types are called).

Runtime data corruption can happen if an indirection is used:

```c++
struct Args
{
    gsl::span<int> span;
};
void fooFuncIndirect(const Args&);
```

If the binary layout of `gsl::actual_span<>` does not exactly match that of `std::span<>` (which is entirely possible), calling this function from Bar would cause data corruption at runtime.

This is why I would argue that gsl-lite should default to `gsl_SPAN_GSL` and `gsl_BYTE_GSL`.

More generally, I feel that aliasing the standard types isn't a very helpful thing to do. In which situation is this supposed to help?

**Comment by martinmoene** [comment]
The idea indeed is/was to default to `gsl_SPAN_DEFAULT` and use `std::span<>` if available, and a dedicated implementation otherwise.

Thanks for making it clear that this is a less-than sane thing to force upon users of this library :)

Defaulting to using the `std::` version of a type is behavior once requested for [one of the vocabulary types](https://github.com/martinmoene/nonstd-lite) on my Github, a behavior I have been replicating for the other types. It is meant as an easy migration path, so that the `std::` version is picked-up automatically if it is/becomes available. However as you point out, there are now-hidden dangers to that approach.

Seems wise to reconsider the default stance at the least.

**Comment by mbeutel** [comment]
I also entertained the idea of introducing "modes" in one of my libraries for quite a while until I came to the conclusion that it should better be avoided.

Let's assume gsl-lite gets a `gsl_CONFIG_SELECT_SPAN` macro as suggested above, and let's again consider my example:

- library Foo, targeting C++14, which uses gsl-lite
- executable Bar, targeting C++20, which uses both Foo and gsl-lite

Foo doesn't configure anything, but Bar wants to be as modern as possible and decides to configure `gsl_CONFIG_SELECT_SPAN=gsl_SPAN_STD`. In CMake:

```cmake
# project Foo
add_library(Foo INTERFACE)
target_link_libraries(Foo INTERFACE gsl::gsl-lite)

# project Bar
add_executable(Bar bar.cpp)
target_link_libraries(Bar PRIVATE Foo::Foo gsl::gsl-lite)
target_compile_definitions(Foo INTERFACE gsl_CONFIG_SELECT_SPAN=gsl_SPAN_STD)
```

Even though gsl-lite sanely defaulted to `gsl_CONFIG_SELECT_SPAN=gsl_SPAN_GSL` when compiling Foo, we run into the same problem as above, i.e. link-time failure if we're lucky, or possibility of runtime data corruption. So picking a sane default didn't save us from insanity.

So perhaps we have to force the library consumer to choose a mode?

```cmake
# project gsl-lite
add_library(gsl-lite-14 INTERFACE)
target_compile_definitions(gsl-lite-14 INTERFACE gsl_CONFIG_SELECT_SPAN=gsl_SPAN_GSL)
add_library(gsl-lite-20 INTERFACE)
target_compile_definitions(gsl-lite-20 INTERFACE gsl_CONFIG_SELECT_SPAN=gsl_SPAN_STD)

# project Foo
add_library(Foo INTERFACE)
target_link_libraries(Foo INTERFACE gsl::gsl-lite-14)

# project Bar
add_executable(Bar bar.cpp)
target_link_libraries(Bar PRIVATE Foo::Foo gsl::gsl-lite-20)
```

Having a conflict here means we end up with two conflicting values for the same macro, which surely raises an error, right? Unfortunately it doesn't. CMake doesn't care and simply passes both macros to the compiler. GCC and Clang kindly warn about a macro redefinition, but neither MSVC nor ICC bother to generate a diagnostic (even with `/W4` and `-Wall -Wextra -pedantic`, respectively); they simply ignore the first value and keep going, cf. https://gcc.godbolt.org/z/9-Q0Kf . So again we get link-time failure or spurious runtime corruption and little or no diagnostics.

As far as I can tell, the only viable way is to manage different modes with different macros and to have a sanity check in gsl-lite like we have for the contract level and assertion macros:

```cmake
# project gsl-lite
add_library(gsl-lite-14 INTERFACE)
target_compile_definitions(gsl-lite-14 INTERFACE gsl_CONFIG_SPAN_MODE_GSL)
add_library(gsl-lite-20 INTERFACE)
target_compile_definitions(gsl-lite-20 INTERFACE gsl_CONFIG_SPAN_MODE_STD)
```

```c++
// gsl-lite.hpp
#if defined( gsl_CONFIG_SPAN_MODE_GSL ) && defined( gsl_CONFIG_SPAN_MODE_STD )
# error Cannot use both gsl-lite-14 and gsl-lite-20 in the same target dependency tree
#endif
```

```cmake
# project Foo
add_library(Foo INTERFACE)
target_link_libraries(Foo INTERFACE gsl::gsl-lite-14)

# project Bar
add_executable(Bar bar.cpp)
target_link_libraries(Bar PRIVATE Foo::Foo gsl::gsl-lite-20)
```

Now we get the desired compile-time failure. I could still manufacture an example in which this slips through unnoticed (by hiding one of the libraries in a private dependency of another dependency) but it would get slightly contrived. Instead, let's think about the consequences of our choice:

- gsl-lite now forces every consumer to pick a "language level mode" (or even worse, arbitrary combinations of fine-grained modes, so the user would have to link `gsl::gsl-lite-std_byte-gsl_span`). What do users choose, and why? Most won't care and simply use the next best target.
- You may be tempted to introduce a default target `gsl::gsl-lite` which selects one of the possible choices – say, `gsl-lite-14`. But then the C++14 mode will be the default forever, because changing it would cause breakage in target chains where some targets selected a mode and others simply kept the default, which happened to be the same mode.
- Even if the users make a qualified choice, will they be aware of the impact? There can only be one "mode" of gsl-lite in every chain of targets, so the library's choice will restrain all projects depending on the library.
- This is even more unfortunate because gsl-lite is supposed to be ubiquitous; everyone should be using it (IMO). There is already a conflict between Microsoft's GSL and gsl-lite, and I don't think adding more conflicts between different modes of gsl-lite is a good idea, as it will only hinder adoption.

Also, there are reasons for wanting modes, but I don't think they apply to gsl-lite. For example, my library Foo might have a function

```c++
void frobnicate(gsl::span<int> data);
```

and it is reasonable that I want to make it usable for callers with either `gsl::span<>` or `std::span<>`. So I could introduce a span alias for either `gsl::span<>` or `std::span<>` in Foo and then introduce a mode to switch between them:

```c++
#ifdef FOO_MODE_GSL
template <typename T> using Span = gsl::span<T>;
#else // FOO_MODE_STD
template <typename T> using Span = std::span<T>;
#endif
void frobnicate(Span<int> data);
```

By having the mode in Foo and not in gsl-lite, I avoid causing incidental conflicts for other libraries using gsl-lite.


However, I think modes are best avoided entirely. My favored approach for `foo::frobnicate()` would be

```c++
#if __has_include(<span>)
 #include <span>
#endif // __has_include(<span>)

void frobnicate(gsl::span<int> data);
#if __has_include(<span>)
void frobnicate(std::span<int> data)
{
    // TODO: call `frobnicate()` with `data` converted to `gsl::span<>`
}
#endif // __has_include(<span>)
```

For "polyfill" libraries such as your nonstd libraries or [MPark.Variant](https://github.com/mpark/variant), it probably makes sense to have explicit opt-in and some code duplication (which can be avoided with macros and nested `#include`s):

```c++
// foo/variant-tools.hpp
#include <variant>
template <typename... AlternativesT>
auto transmogrify(std::variant<AlternativesT...>)
{
    ...
}

// foo/variant-tools-mpark.hpp
#include <mpark/variant.hpp>
template <typename... AlternativesT>
auto transmogrify(mpark::variant<AlternativesT...>)
{
    ...
}
```

**Comment by mbeutel** [comment]
> However, I think modes are best avoided entirely. My favored approach for `foo::frobnicate()` would be
> 
> ```c++
> #if __has_include(<span>)
>  #include <span>
> #endif // __has_include(<span>)
> 
> void frobnicate(gsl::span<int> data);
> #if __has_include(<span>)
> void frobnicate(std::span<int> data)
> {
>     // TODO: call `frobnicate()` with `data` converted to `gsl::span<>`
> }
> #endif // __has_include(<span>)
> ```

Admittedly, this has the problem that we'd get a lot of ambiguity from span constructors, so we cannot say `frobnicate(int_vector)` without interposing either `std::span()` or `gsl::make_span()`, and this problem will surface only when `<span>` becomes available. So this is not a good design either.

Perhaps it's better to use different names in that particular case (`frobnicate()` and `frobnicate_gsl()`?).

**Comment by mbeutel** [comment]
For the reasons explaind above, I'd rather not introduce a `gsl_CONFIG_SELECT_SPAN` option.
