### ISSUE TITLE
Add test with not_null<unique_ptr<T>>

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/gsl-lite#129]
See M-GSL PR 675.

**Comment by petamas** [comment]
I've been playing around with not_null<unique_ptr<T>>, and found a few problems.

I'll use these helpers in my examples:
`
using point = std::pair<int, int>;

template <typename T>
using nn_unique_ptr = gsl::not_null<std::unique_ptr<T>>;

template <typename T, typename... Args>
nn_unique_ptr<T> nn_make_unique(Args &&... args) {
	return nn_unique_ptr<T>(std::unique_ptr<T>(new T(std::forward<Args>(args)...)));
}
`

### operator-> is not working by default
This code does not compile:
`
TEST(GslNotNull, NNMakeUniqueWorks)
{	
	nn_unique_ptr<point> nnp = nn_make_unique<point>(1, 3);
	EXPECT_EQ(nnp->first, 1);
	EXPECT_EQ(nnp->second, 3);
}
`
See: https://gcc.godbolt.org/z/GmDX_I

The problem is that operator-> tries to return a unique_ptr<point> by value, but since it is move-only, it cannot. If we use -Dgsl_CONFIG_NOT_NULL_GET_BY_CONST_REF, this problem goes away.

### not_null<unique_ptr<T>>  cannot be converted to not_null<unique_ptr<const T>>

This code does not compile (not even with -Dgsl_CONFIG_NOT_NULL_GET_BY_CONST_REF):
`
TEST(GslNotNull, NNUniqueCanBeConvertedToConstUnique)
{
	nn_unique_ptr<const point> nnp = nn_make_unique<point>(1, 3);
	EXPECT_EQ(nnp->first, 1);
	EXPECT_EQ(nnp->second, 3);
}
`

See: https://gcc.godbolt.org/z/nNXvuC

The problem is that the not_null<U> constructor has a const& parameter,  it doesn't have a "move" version. Similarly, get() lacks a "moving" version.

### not_null<unique_ptr<T>> cannot be converted to not_null<shared_ptr<T>>

This code does not compile (not even with -Dgsl_CONFIG_NOT_NULL_GET_BY_CONST_REF):
`
TEST(GslNotNull, NNUniqueCanBeConvertedToShared)
{
	nn_shared_ptr<point> nnp = nn_make_unique<point>(1, 3);
	EXPECT_EQ(nnp->first, 1);
	EXPECT_EQ(nnp->second, 3);
}
`

See https://gcc.godbolt.org/z/D-9dk0

This is a variation of the above problem, with the same RC.


I'll submit a PR with some unit tests and potential fixes for these problems.

**Comment by petamas** [comment]
@mbeutel: I think this can be closed now :)

**Comment by mbeutel** [comment]
Indeed. Thanks for your contribution.
