### ISSUE TITLE
Adapt CmakeLists.txt for easier consumption of GSL Lite by another project

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/gsl-lite#38]
Changes:
- Use `target_include_directories` over `include_directories`.
- Use `INTERFACE` library.
- Add GSL project to `tests/CMakeLists.txt`.

**Note**: requires CMake 2.8.12 instead of 2.8.11.2 (Travis).

See M-GSL [PR #370](https://github.com/Microsoft/GSL/pull/370).

**Comment by nholthaus** [comment]
In reality, using interface libraries may require CMake 3.3, at least if your library clients want to be able to depend on them, due to [this bug](https://cmake.org/Bug/view.php?id=15414). This [SO question](http://stackoverflow.com/questions/35630755/propagate-dependencies-to-header-only-externalproject-with-cmake) may also be informative.
